### ISSUE TITLE
es-check es5 no match destructuring assignment 

### ISSUE THREAD

**Issue by yukinotech** [yowainwright/es-check#107]
hi, it seem that es-check doesn`t match destructuring assignment  in es5.

es-check version `6.0.0`

`./code/script.js` 

```
let [a1, a2, a3] = [1, 2, 3]
```

run script
```
es-check es5 ./code/*.js
```
the stdout is
`ES-Check: there were no ES version matching errors!`

es-check es5 no match destructuring assignment which is es6 syntax. 

Is this a bug ?

**Comment by noahnu** [comment]
The "let" is interpreted as a keyword in strict mode only for ES5. Outside of strict mode, what you've written is similar to:

```
myVariable [a1, a2, a3] = [1, 2, 3]
```

where myVariable is named "let" in your code. This is then interpreted with the grammar

```
<Identifier>[<SequenceExpression>] <Assignment> <Array>
```

The `[a1, a2, a3]` is just indexing into the object "let" (or `myVariable` in my example). The `a1, a2, a3` isn't treated like an array, but instead like an expression using the comma operator. The comma operator evaluates expression expression and returns the last item in the sequence. So the code becomes:

```
myVariable[a3] = [1, 2, 3]
```

which is perfectly valid ES5 code

**Comment by yowainwright** [comment]
Closing b/c of @noahnu thoughtful response. 🙏  

Thanks for observation @yukinotech !
