### ISSUE TITLE
"Must provide pattern" error when using `--module` in 6.1.0

### ISSUE THREAD

**Issue by stevehobbsdev** [yowainwright/es-check#139]
## Requested Update

I get a "must provide pattern" error for this command after upgrading to 6.1.0 from 6.0.0, without any other changes.

```
node ./node_modules/.bin/es-check es2015 --module 'dist/auth0-spa-js.production.esm.js'
```

I added some logging to see what's going on, it looks like the filename isn't being passed through the options:

```
.action(({ logger, args, options }) => {
    const configFilePath = path.resolve(process.cwd(), '.escheckrc')

    // Some basic logging
    console.log(options)
    console.log(args);

    // ...
})
```

Yields:

```
{ module: false, allowHashBang: false }
{ ecmaVersion: 'es2015' }
```

Not specifying `--module` sends the filename correctly, but of course the command fails.

```
{ module: false, allowHashBang: false }
{
  ecmaVersion: 'es2015',
  files: [ 'dist/auth0-spa-js.production.esm.js' ]
}
```

Could [this upgrade](https://github.com/yowainwright/es-check/pull/133) have caused it?

## Why Is This Update Needed?

Would like to be able to use 6.1.0 and generally keep up to date, otherwise I can pin to 6.0.0.

## Are There Examples Of This Requested Update Elsewhere?

I couldn't find one, but apologies if it's a known issue.

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
Ah crap @stevehobbsdev, I'll look into it. Thanks for letting me know! 

I'll look into this ASAP.

**Comment by StudioMaX** [comment]
In the README, I did not see a description in which order to set the arguments and options.
But in the tests, I see that additional options are added at the end of the command, after the list of files. Like this:
``
node index.js es6 ./tests/modules/*.js --module
``


So, could try to check
``
node ./node_modules/.bin/es-check es2015 'dist/auth0-spa-js.production.esm.js' --module
``
instead of 
``
node ./node_modules/.bin/es-check es2015 --module 'dist/auth0-spa-js.production.esm.js'
``
?

**Comment by yowainwright** [comment]
@StudioMaX Thanks for your speedy thoughtful response! 

@stevehobbsdev does Pavel's observation help before a fix is looked into/provided?

**Comment by stevehobbsdev** [comment]
I will try when I'm back at my machine.

However, just wanted to note that it's at the least a breaking change, as the command as written in my original comment, with `--module` before the file path, works in 6.0.0. Apologies if this was called out in a release note somewhere and I missed it.

**Comment by stevehobbsdev** [comment]
Confirmed that moving `--module` to the end of the command has fixed it 👍🏻 

Would suggest that a fix is looked into nonetheless as simply upgrading this minor version is effectively a breaking change.

**Comment by yowainwright** [comment]
@stevehobbsdev agreed 💯 ! 

I assume you can tell this was an accidental breaking change. 😞 

Tests will be added and hopefully, we can fix this compatibility as soon as possible. 
Thanks for bringing this up! 

Thank you as well @StudioMaX!

**Comment by stevehobbsdev** [comment]
> I assume you can tell this was an accidental breaking change

Oh of course, all good. Happens to the best of us 😃

Glad I could be of help in raising it 🙌
