### ISSUE TITLE
Cannot use this project with `yarn` or `npm`

### ISSUE THREAD

**Issue by arthurfiorette** [yowainwright/es-check#153]
When upgradint to v6.2.0, this error occurs:

```
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
║   For more details, go to https://pnpm.js.org/              ║
║                                                             ║
╚═════════════════════════════════════════════════════════════╝
``` 

Why you are requiring `pnpm`?

https://github.com/arthurfiorette/fast-defer/runs/4980449823?check_suite_focus=true

**Comment by droobertzka** [comment]
+1

**Comment by andersk** [comment]
@yowainwright Perhaps you meant to require `pnpm` for development of es-check itself? As-is, you are also requiring `pnpm` for all projects that *depend* on es-check too.

**Comment by yowainwright** [comment]
@andersk @arthurfiorette @droobertzka holy s**t! 😞 

I'm sorry!

Thank you!

Fixing.
