### ISSUE TITLE
Add `es2022` and `es2023` support

### ISSUE THREAD

**Issue by mikkixlisa** [yowainwright/es-check#174]
## Requested Update

Add `es2022` and `es2023` support.

## Why Is This Update Needed?

`acorn` already supports both `es2022` and `es2023`, but they're filtered by the `es-check` ECMA version check.

## Are There Examples Of This Requested Update Elsewhere?

Not sure, if this is relevant.

**Comment by yowainwright** [comment]
@mikkixlisa thanks for calling this out and the sponsorship! It means a lot 🙏

**Comment by mikkixlisa** [comment]
Cheers mate!
