### ISSUE TITLE
Flag option for specifying files

### ISSUE THREAD

**Issue by merrywhether** [yowainwright/es-check#197]
## Requested Update

Add a way to describe files via a flag (something like `-f`/`--files`).

## Why Is This Update Needed?

The would make it easier to work with a configuration file in the case where you want to vary which files you check without changing the ES version. Having files only come via positional arguments forces users to redeclare the ES version unnecessarily (getting `error: Invalid ecmaScript version, please pass a valid version, use --help for help` if they try to omit it and go straight to file paths).

### Example

Say you have a configuration file like this:
```json
{
  "ecmaVersion": "es6",
  "module": false,
  "files": "./dist/**/*.js",
  "not": ["./dist/skip/*.js"]
}
```

If you want to change which files are checked, you currently have to do this, duplicating the ES version declaration and introducing the possibility for drift:
```sh
es-check es6 './dist/app/**/*.js'
```

With a flag, you could do this:
```sh
es-check -f './dist/app/**/*.js'
```

This would be a small QoL improvement. The existing functionality would still be the primary way to declare files and would take precedence over a flag declaration in the event of duplication.

I'm happy to contribute this if the idea is accepted.

## Are There Examples Of This Requested Update Elsewhere?

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
This is thoughtful @merrywhether ! Will look to add this or feel free to submit a PR.
