### ISSUE TITLE
Update copyright in `LICENSE`

### ISSUE THREAD

**Issue by merrywhether** [yowainwright/es-check#202]
## Requested Update

This is more of a note that the `LICENSE` still [attributes copyright to Dollar Shave Club as of 2017](https://github.com/yowainwright/es-check/blob/main/LICENSE#L3) and you might want to update it with a new line indicating the ownership lineage.

## Why Is This Update Needed?

Generally ideal to keep the license and copyright up to date.

## Are There Examples Of This Requested Update Elsewhere?

https://github.com/orgs/community/discussions/47161

**Comment by yowainwright** [comment]
@merrywhether sorry for the slow reply. What LICENSE do you feel? MIT

**Comment by merrywhether** [comment]
License type doesn't need to change, just adding a line showing new ownership. Made a quick PR for you.
