### ISSUE TITLE
The output for a successful ES-Check run is logged as an error

### ISSUE THREAD

**Issue by nicholashza** [yowainwright/es-check#31]
https://github.com/yowainwright/es-check/blob/2a5eefd677faa7a89c9283ea6b6fe462c50e1fbd/index.js#L203

Is this by design? I can submit a PR switching this to be an info log if required. There is a PR on the archived project that wraps this log with the quiet flag to obey the quiet setting, but I would think correctly info logging would be more correct as this is not an error being logged.

**Comment by yowainwright** [comment]
@nicholashza feel free to submit a PR! Sorry it took me so long to get back to you 🙂
