### ISSUE TITLE
Failure to apply `not` option in .escheckrc

### ISSUE THREAD

**Issue by noah-potter** [yowainwright/es-check#49]
## Requested Update
Update logic when falling back to `not` option in .escheckrc

## Why Is This Update Needed?
Currently the `not` option isn't applied.

## Are There Examples Of This Requested Update Elsewhere?
No

## Misc
Caporal returns  `[]` by default since the `prog.LIST` validator is used. This means `options.not` is never falsy and will not use `config.not`.

**Comment by yowainwright** [comment]
@noah-potter care to submit a PR? 🙂

**Comment by noah-potter** [comment]
Sure!
