### ISSUE TITLE
Update acorn to latest version

### ISSUE THREAD

**Issue by andrewdavey** [yowainwright/es-check#54]
When running es-check over my production build, I get this error:

```
          ES-Check Error:
          ----
          · erroring file: ./build/vendor-495a726ca52bcd7d3511.js
          · error: SyntaxError: Parenthesized pattern (124:4651)
          · see the printed err.stack below for context
          ----

          SyntaxError: Parenthesized pattern (124:4651)
```

It seems this might be a bug in the older version of acorn. Is it possible for es-check to use the latest version instead please?

**Comment by yowainwright** [comment]
@andrewdavey your comment was read! 🙂  I'm hesitant to jump until I have a full solution to some of the issues we encountered when trying to [upgrade recently](https://github.com/yowainwright/es-check/pull/26).

**Comment by andrewdavey** [comment]
OK no worries. This isn't a big blocker for me. I appreciate you letting me know.

**Comment by noahnu** [comment]
Is there a workaround for this? We have es-check configured as a required check in our CI pipeline.

**Comment by mjancarik** [comment]
Hi,

I have a similar problem when I am running es-check over my files with es11 settings. I updated on my local machine to the latest version of acorn and everything works. Do you have some progress?

Thanks

**Comment by yowainwright** [comment]
@mjancarik mind submitting a pr which ensures that tests pass?

**Comment by noahnu** [comment]
@yowainwright I put up a PR here: https://github.com/yowainwright/es-check/pull/98

**Comment by yowainwright** [comment]
Thanks @noahnu! 🙏 I'll go over this asap. Most likely tomorrow!
